// Downloads the words/groups for every puzzle listed in puzzles.js into games.js.
// Usage: node fetch-puzzles.js   (only fetches puzzles not already in games.js)
const fs = require("fs");
const path = require("path");

const dir = __dirname;
const load = (file) => {
  const window = {};
  const src = path.join(dir, file);
  if (fs.existsSync(src)) new Function("window", fs.readFileSync(src, "utf8"))(window);
  return window;
};

const { PUZZLES } = load("puzzles.js");
const games = load("games.js").GAMES || {};
const ids = [...PUZZLES.ARCHIVE, ...PUZZLES.DATED.map((x) => x[1])];
const missing = ids.filter((id) => !games[id]);

(async () => {
  const failed = [];
  for (let i = 0; i < missing.length; i += 8) {
    await Promise.all(missing.slice(i, i + 8).map(async (id) => {
      try {
        const html = await (await fetch("https://connections.swellgarfo.com/game/" + id)).text();
        const m = html.match(/<script id="__NEXT_DATA__"[^>]*>(.*?)<\/script>/s);
        const p = JSON.parse(m[1]).props.pageProps;
        games[id] = {
          title: p.puzzleMetadata?.title || "",
          author: p.puzzleMetadata?.author || "",
          groups: p.answers.map((a) => ({ d: a.description, w: a.words, c: a.color })),
        };
      } catch (e) {
        failed.push(id);
      }
    }));
  }
  const body = ids.filter((id) => games[id]).map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(games[id])}`).join(",\n");
  fs.writeFileSync(path.join(dir, "games.js"), `// Generated by fetch-puzzles.js. Do not edit by hand.\nwindow.GAMES = {\n${body}\n};\n`);
  console.log(`fetched ${missing.length - failed.length} new, ${Object.keys(games).length} total`);
  if (failed.length) console.log("failed:", failed.join(", "));
})();
