// Shared helpers for reading/writing the site's data files (puzzles.js, games.js).
const fs = require("fs");
const path = require("path");

const dir = __dirname;
const PUZZLES_FILE = path.join(dir, "puzzles.js");
const GAMES_FILE = path.join(dir, "games.js");
const COLORS = ["#fbd400", "#69e352", "#5492ff", "#df7bea"]; // yellow, green, blue, purple (easy -> hard)

function loadWindowFile(file) {
  const window = {};
  if (fs.existsSync(file)) new Function("window", fs.readFileSync(file, "utf8"))(window);
  return window;
}
const loadPuzzles = () => loadWindowFile(PUZZLES_FILE).PUZZLES;
const loadGames = () => loadWindowFile(GAMES_FILE).GAMES || {};
const allIds = (P) => [...P.ARCHIVE, ...P.DATED.map((x) => x[1])];

function writeGames(games) {
  const P = loadPuzzles();
  const ids = allIds(P).filter((id) => games[id]);
  const body = ids.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(games[id])}`).join(",\n");
  fs.writeFileSync(GAMES_FILE, `// Generated by fetch-puzzles.js / puzzle studio. Do not edit by hand.\nwindow.GAMES = {\n${body}\n};\n`);
}

const today = () => { const d = new Date(); return `${d.getDate()}/${d.getMonth() + 1}/${d.getFullYear()}`; };
const dateKey = (s) => { const [d, m, y] = s.split("/").map(Number); return y * 10000 + m * 100 + d; };
function validDate(s) {
  const m = String(s).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  return !!m && +m[1] >= 1 && +m[1] <= 31 && +m[2] >= 1 && +m[2] <= 12;
}

// Inserts [date, id] into DATED keeping newest-first order. Returns the puzzle number.
function insertDated(date, id) {
  const P = loadPuzzles();
  if (allIds(P).includes(id)) throw new Error("already on the site");
  if (!validDate(date)) throw new Error("date must be D/M/YYYY");
  const pos = P.DATED.findIndex(([d]) => dateKey(d) <= dateKey(date));
  if (pos === -1) throw new Error("date is older than every dated puzzle on the site");
  const src = fs.readFileSync(PUZZLES_FILE, "utf8");
  const anchor = `    [${JSON.stringify(P.DATED[pos][0])}, ${JSON.stringify(P.DATED[pos][1])}]`;
  if (!src.includes(anchor)) throw new Error("puzzles.js has an unexpected format");
  const line = `    [${JSON.stringify(date)}, ${JSON.stringify(id)}],\n`;
  fs.writeFileSync(PUZZLES_FILE, src.replace(anchor, line + anchor));
  return P.ARCHIVE.length + (P.DATED.length - pos) + 1;
}

function extractSwellgarfoId(text) {
  const m = String(text).match(/game\/([-\w]+)/) || String(text).trim().match(/^(-[-\w]{10,})$/);
  return m ? m[1] : null;
}

async function fetchSwellgarfo(id) {
  const html = await (await fetch("https://connections.swellgarfo.com/game/" + id)).text();
  const m = html.match(/<script id="__NEXT_DATA__"[^>]*>(.*?)<\/script>/s);
  const p = m && JSON.parse(m[1]).props.pageProps;
  if (!p || !p.answers || p.answers.length !== 4) throw new Error("puzzle not found on swellgarfo");
  return {
    title: p.puzzleMetadata?.title || "",
    author: p.puzzleMetadata?.author || "",
    groups: p.answers.map((a) => ({ d: a.description, w: a.words, c: a.color })),
  };
}

// Validates a hand-made puzzle: 4 groups (easy -> hard), each a description + 4 words, 16 distinct words.
function buildOwnGame({ title = "", author = "", groups }) {
  if (!Array.isArray(groups) || groups.length !== 4) throw new Error("need exactly 4 groups");
  const out = groups.map((g, i) => {
    const d = String(g.d || "").trim();
    const w = (g.w || []).map((x) => String(x).trim());
    if (!d) throw new Error(`group ${i + 1} needs a description`);
    if (w.length !== 4 || w.some((x) => !x)) throw new Error(`group ${i + 1} needs 4 words`);
    return { d, w, c: COLORS[i] };
  });
  const words = out.flatMap((g) => g.w.map((x) => x.toLowerCase()));
  const dup = words.find((x, i) => words.indexOf(x) !== i);
  if (dup) throw new Error(`the word "${dup}" appears twice`);
  return { title: String(title).trim(), author: String(author).trim(), groups: out };
}

const newOwnId = () => "own-" + Date.now().toString(36);

module.exports = {
  loadPuzzles, loadGames, writeGames, insertDated, today, validDate,
  extractSwellgarfoId, fetchSwellgarfo, buildOwnGame, newOwnId, allIds,
};
