// Pure puzzle-data logic shared by the local studio (studio.js) and the online studio (api/*).
// Works on file *contents* (strings), so callers decide where the files live (disk or GitHub).

const COLORS = ["#fbd400", "#69e352", "#5492ff", "#df7bea"]; // yellow, green, blue, purple (easy -> hard)

function evalWindowFile(src) {
  const window = {};
  if (src) new Function("window", src)(window);
  return window;
}
const parsePuzzles = (src) => evalWindowFile(src).PUZZLES;
const parseGames = (src) => evalWindowFile(src).GAMES || {};
const allIds = (P) => [...P.ARCHIVE, ...P.DATED.map((x) => x[1])];
const totalCount = (P) => P.ARCHIVE.length + P.DATED.length;

function serializeGames(P, games) {
  const ids = allIds(P).filter((id) => games[id]);
  const body = ids.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(games[id])}`).join(",\n");
  return `// Generated by the puzzle studio. Do not edit by hand.\nwindow.GAMES = {\n${body}\n};\n`;
}

// Today's date as D/M/YYYY in Israel time (servers run in UTC).
function today() {
  const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Jerusalem", day: "numeric", month: "numeric", year: "numeric" }).formatToParts(new Date());
  const get = (t) => parts.find((p) => p.type === t).value;
  return `${Number(get("day"))}/${Number(get("month"))}/${get("year")}`;
}
const dateKey = (s) => { const [d, m, y] = s.split("/").map(Number); return y * 10000 + m * 100 + d; };
function validDate(s) {
  const m = String(s).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  return !!m && +m[1] >= 1 && +m[1] <= 31 && +m[2] >= 1 && +m[2] <= 12;
}

// Inserts [date, id] into DATED (newest first). Returns the new puzzles.js source and the puzzle number.
function insertDated(puzzlesSrc, date, id) {
  const P = parsePuzzles(puzzlesSrc);
  if (allIds(P).includes(id)) throw new Error("already on the site");
  if (!validDate(date)) throw new Error("date must be D/M/YYYY");
  const pos = P.DATED.findIndex(([d]) => dateKey(d) <= dateKey(date));
  if (pos === -1) throw new Error("date is older than every dated puzzle on the site");
  const anchor = `    [${JSON.stringify(P.DATED[pos][0])}, ${JSON.stringify(P.DATED[pos][1])}]`;
  if (!puzzlesSrc.includes(anchor)) throw new Error("puzzles.js has an unexpected format");
  const line = `    [${JSON.stringify(date)}, ${JSON.stringify(id)}],\n`;
  return { src: puzzlesSrc.replace(anchor, line + anchor), n: P.ARCHIVE.length + (P.DATED.length - pos) + 1 };
}

// Adds a puzzle to both data files. Returns { puzzlesSrc, gamesSrc, n }.
function addPuzzle(puzzlesSrc, gamesSrc, date, id, game) {
  const { src, n } = insertDated(puzzlesSrc, date, id);
  const games = parseGames(gamesSrc);
  games[id] = game;
  return { puzzlesSrc: src, gamesSrc: serializeGames(parsePuzzles(src), games), n };
}

function extractSwellgarfoId(text) {
  const m = String(text).match(/game\/([-\w]+)/) || String(text).trim().match(/^(-[-\w]{10,})$/);
  return m ? m[1] : null;
}

async function fetchSwellgarfo(id) {
  const html = await (await fetch("https://connections.swellgarfo.com/game/" + id)).text();
  const m = html.match(/<script id="__NEXT_DATA__"[^>]*>(.*?)<\/script>/s);
  const p = m && JSON.parse(m[1]).props.pageProps;
  if (!p || !p.answers || p.answers.length !== 4) throw new Error("puzzle not found on swellgarfo");
  return {
    title: p.puzzleMetadata?.title || "",
    author: p.puzzleMetadata?.author || "",
    groups: p.answers.map((a) => ({ d: a.description, w: a.words, c: a.color })),
  };
}

// Validates a hand-made puzzle: 4 groups (easy -> hard), each a description + 4 words, 16 distinct words.
function buildOwnGame({ title = "", author = "", groups, intl = false }) {
  if (!Array.isArray(groups) || groups.length !== 4) throw new Error("need exactly 4 groups");
  const out = groups.map((g, i) => {
    const d = String(g.d || "").trim();
    const w = (g.w || []).map((x) => String(x).trim());
    if (!d) throw new Error(`group ${i + 1} needs a description`);
    if (w.length !== 4 || w.some((x) => !x)) throw new Error(`group ${i + 1} needs 4 words`);
    return { d, w, c: COLORS[i] };
  });
  const words = out.flatMap((g) => g.w.map((x) => x.toLowerCase()));
  const dup = words.find((x, i) => words.indexOf(x) !== i);
  if (dup) throw new Error(`the word "${dup}" appears twice`);
  const game = { title: String(title).trim(), author: String(author).trim(), groups: out };
  if (intl) game.intl = true; // marked by hand as playable without Hebrew
  return game;
}

const newOwnId = () => "own-" + Date.now().toString(36);

// Turns a studio request into { id, game }: either a hand-made puzzle or one fetched from swellgarfo.
async function resolveRequest(kind, body, existingIds) {
  if (kind === "link") {
    const id = extractSwellgarfoId(body.link);
    if (!id) throw new Error("that doesn't look like a swellgarfo link");
    if (existingIds.includes(id)) throw new Error("this puzzle is already on the site");
    return { id, game: await fetchSwellgarfo(id) };
  }
  return { id: newOwnId(), game: buildOwnGame(body) };
}

module.exports = {
  parsePuzzles, parseGames, allIds, totalCount, serializeGames, today, validDate,
  insertDated, addPuzzle, extractSwellgarfoId, fetchSwellgarfo, buildOwnGame, newOwnId, resolveRequest,
};
